### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by DaniGuardiola** [justinthec/agar.io-key-movement#1]
Hey, did you find a solution to stopping? I developed a similar script but I don't know how to stop. As you may already know, simulating mousemove in the center does not work. Thanks for your time.

**Comment by Gjum** [comment]
The server moves you until your blob reaches your sent coordinates. So when you do not send any mouse updates, the blob eventually stops.

**Comment by DaniGuardiola** [comment]
I know, but try with the mouse, it stops instantly. If you simulate mousemove in the center it does not, so it may be detecting some kind of "natural movement" or something similar. It's not the lag because I'm running a local server so it is instantaneous. Any ideas?

**Comment by DaniGuardiola** [comment]
BTW, if you wanna contribute to my Chrome extension, you can at https://github.com/DaniGuardiola/agario-keyboard ^^

**Comment by justinthec** [comment]
I think the "natural movement" can be simulated by changing the stop command to setting the cursor to Center immediately to a two step sequence. 
1. Set the cursor to Center + (some small offset in the direction we are moving). 
2. Set the cursor to center. 

If that doesn't work maybe we need to slowly bring the cursor to Center over x amount of time. Other than that it feels the effort outweighs the payoff.

**Comment by DaniGuardiola** [comment]
Yeah, I already tried that some time ago. I'm gonna try again, and progressively add steps until it works. What I don't know yet is how can i make these movement cancelable.. If I use timeouts I need a variable for each step to be able to clearTimeout it later. Any idea on how to make it simpler?

**Comment by Gjum** [comment]
What do you mean by _simulate mousemove in the center_?  When I send a position and stop sending any more, the blob moves to that position and stops.

By the way, what are you trying to achieve by stopping the blob?

**Comment by DaniGuardiola** [comment]
@Gjum to move the blob in my Chrome extension, I simulate a mousemove in the canvas. This script does too. The thing is that when you stop pushing buttons, the blob should stop instantly, just like when you are playing with the mouse and you move the cursor to the center (where the player is). The problem is that it does not seem to work. It just keeps going until it stops some time later.
That is why @justinthec and I are trying to figure out a way to simulate that mouse movement, because moving it to the center does not work.

**Comment by Gjum** [comment]
Can you show some code?

**Comment by DaniGuardiola** [comment]
@Gjum https://github.com/DaniGuardiola/agario-keyboard
Take a look at move(), there's an empty if for executing some some in the case of 'stop'. Using moveTo(x, y) and some good timing i might be able to simulate the "natural behavior" but I need ideas because having a timeout for each step does not seem like an option (considering that I would have to cancel all of them if the user moves when the animation did not end yet).

**Comment by Gjum** [comment]
I'd like to try out both scripts to try something out, but sadly neither of them work since the recent facebook update :( I think pointing to the screen center may not work because of client-side frame interpolation, but that's just a theory.

**Comment by DaniGuardiola** [comment]
Mine works after the facebook update. Will update you if I find a solution.

**Comment by DaniGuardiola** [comment]
@Gjum I found a solution but I think I can still improve it.
Check:
https://github.com/DaniGuardiola/agario-keyboard/commit/67ae548740de00fcda92ae89d23c6b903dc5e9e1

And to try it live:
https://chrome.google.com/webstore/detail/pbobiamfiefihckgfbppiigkfbkbmhlm

**Comment by DaniGuardiola** [comment]
Movimiento EBR Madrid


Únete a Dani Guardiola y 22 otros activistas y librepensantes en Madrid Sé el primero en enterarte de nuevos Meetups y novedades en tu área.


Somos un grupo de personas con diferentes trayectorias e ideas unidas por un objetivo: la Economía Basada en Recursos. Organizamos un encuentro temático mensual en Madrid y llevamos a cabo todo tipo d...

--------------------------------------

Aceptar invitación
https://secure.meetup.com/n/?s=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXN0IjoiaHR0cHM6Ly9zZWN1cmUubWVldHVwLmNvbS9yZWdpc3Rlci8_Z2o9ZWo0cyZjPTE5MDYzNDY2Jl94dGQ9Z3F0bGJXRnBiRjlqYkdsamE5b0FKR0l3T0RWalptTTJMV1V5WlRjdE5EUXhOQzA0TkRneExXRmpORFEzWldGak1tUmpNYXBwYm5acGRHVmxYMmxrcHpJek1EQXpPVGsmcmc9ZWo0cyZ0YXJnZXRVcmk9aHR0cCUzQSUyRiUyRnd3dy5tZWV0dXAuY29tJTJGTW92aW1pZW50by1FQlItTWFkcmlkJTJGJTNGZ2olM0RlajRzJTI2cmclM0RlajRzIiwiaG9vayI6ImludiIsImVtYWlsIjoicmVwbHkrMDA4NzNjZjcxNzViOWI2YThmNzEzNzVhNDRmYmY0OWRlYjU1MTdlZjYwN2M4MTkwOTJjZjAwMDAwMDAxMTFiN2IyY2M5MmExNjljZTA1OTZkYThjQHJlcGx5LmdpdGh1Yi5jb20iLCJpbnZpdGVyX2lkIjoxODM1OTczNDAsImdyb3VwX2lkIjoxOTA2MzQ2NiwiZXhwIjoxNDQ3NDg5MTA4LCJpYXQiOjE0NDcwNTcxMDgsImp0aSI6IjYzODdhZjhlLTg2YmMtNDA3Yy04YzdmLWI5M2Y5MWY4MDY4YyJ9.BrHMAQCGALCuCxkURQzruyVcx1xAYHfaQHawnOT10l4%3D

--------------------------------------

Este mensaje fué enviado por Meetup a nombre de Dani Guardiola http://www.meetup.com/Movimiento-EBR-Madrid/members/183597340/ del grupo Movimiento EBR Madrid
